### ISSUE TITLE
Crash when going back to parent comment

### ISSUE THREAD

**Issue by lhark** [Kennyc1012/Opengur#103] opened 2015-06-10 16:01 UTC
When reading nested comments, if you try to go back to the previous comment, either via the "previous comment" button or the physical back button, it first shows a blank page for the 1st level, and then if you try again, the app crashes.

**Comment by Kennyc1012** [comment] 2015-06-10 19:13
I am unable to reproduce this, what device, OS, and app version are you using?

**Comment by lhark** [comment] 2015-06-10 22:54
* Xperia ray
* android 4.0.4, build 4.1.B.0.587
* Opengur 2.9.0

The problem has been there for a few versions now.

**Comment by lhark** [comment] 2015-06-10 23:07
Here's the crash log
And to reproduce the crash, you need to dive at least 3 levels deep or else the "previous comment" button does not appear
```
W/dalvikvm( 2700): threadid=1: thread exiting with uncaught exception (group=0x2b542210)
W/ActivityManager(  286): Unable to start service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms }: not found
E/AndroidRuntime( 2700): FATAL EXCEPTION: main
E/AndroidRuntime( 2700): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime( 2700): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
E/AndroidRuntime( 2700): 	at java.util.ArrayList.get(ArrayList.java:304)
E/AndroidRuntime( 2700): 	at com.kenny.openimgur.adapters.ImgurBaseAdapter.getItem(ImgurBaseAdapter.java:131)
E/AndroidRuntime( 2700): 	at com.kenny.openimgur.activities.ViewActivity.onListItemClick(ViewActivity.java:1035)
E/AndroidRuntime( 2700): 	at com.kenny.openimgur.activities.ViewActivity.access$400(ViewActivity.java:88)
E/AndroidRuntime( 2700): 	at com.kenny.openimgur.activities.ViewActivity$2.onItemClick(ViewActivity.java:268)
E/AndroidRuntime( 2700): 	at android.widget.AdapterView.performItemClick(AdapterView.java:292)
E/AndroidRuntime( 2700): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1065)
E/AndroidRuntime( 2700): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2522)
E/AndroidRuntime( 2700): 	at android.widget.AbsListView$1.run(AbsListView.java:3183)
E/AndroidRuntime( 2700): 	at android.os.Handler.handleCallback(Handler.java:605)
E/AndroidRuntime( 2700): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 2700): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2700): 	at android.app.ActivityThread.main(ActivityThread.java:4441)
E/AndroidRuntime( 2700): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2700): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2700): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime( 2700): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime( 2700): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  286):   Force finishing activity com.kennyc.open.imgur/com.kenny.openimgur.activities.ViewActivity
W/ActivityManager(  286): Activity pause timeout for ActivityRecord{2c2462d8 com.kennyc.open.imgur/com.kenny.openimgur.activities.ViewActivity}
```

**Comment by Kennyc1012** [comment] 2015-06-10 23:42
The previous comment button should appear once you down into any level, does it not for you?

**Comment by lhark** [comment] 2015-06-10 23:59
If i go down 2 levels, i can then press it once before the page goes completly blank.
However, if i dive further than 3 levels, when i go back up the button stays there.

**Comment by Kennyc1012** [comment] 2015-06-11 13:30
Comments are being completely redone in the near future, so I probably won't be fixing this. Also, I will probably be dropping support for 4.0.4 pretty soon, Sorry :/

**Closed by Kennyc1012** 2015-06-11 13:30 UTC
Labels: wontfix
